"use client";

import { useState, useEffect, FormEvent } from "react";
import { Product } from "../types/Product";
import { getFecha } from "../utils/validations";

interface ResourceFormProps {
  onSave: (resource: Product) => void;
  onCancel?: () => void;
  resourceToEdit?: Product | null;
  existingResources?: Product[];
  accent?: {
    bgPrimary: string;
    borderFocus: string;
    text?: string;
  };
}

export default function ResourceForm({
  onSave,
  onCancel,
  resourceToEdit,
  existingResources = [],
  accent = {
    bgPrimary: "bg-amber-500 hover:bg-amber-600 text-white",
    borderFocus: "focus:border-amber-500 focus:ring-amber-500",
  },
}: ResourceFormProps) {
  const initialFormState = {
    nombre: "",
    categoria: "",
    cantidad: 1,
    estado: "Disponible" as Product["estado"],
    ubicacion: "",
    responsable: "",
    fechaIngreso: getFecha(),
    descripcion: "",
  };

  const [formData, setFormData] = useState(initialFormState);

  useEffect(() => {
    if (resourceToEdit) {
      const fechaIngreso =
        resourceToEdit.fechaIngreso instanceof Date
          ? resourceToEdit.fechaIngreso.toISOString().split("T")[0]
          : resourceToEdit.fechaIngreso;

      setFormData({
        nombre: resourceToEdit.nombre,
        categoria: resourceToEdit.categoria,
        cantidad: resourceToEdit.cantidad,
        estado: resourceToEdit.estado,
        ubicacion: resourceToEdit.ubicacion,
        responsable: resourceToEdit.responsable || "",
        fechaIngreso,
        descripcion: resourceToEdit.descripcion || "",
      });
    } else {
      setFormData(initialFormState);
    }
  }, [resourceToEdit]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;

    setFormData((prev) => ({
      ...prev,
      [name]: name === "cantidad" ? Number(value) : value,
    }));
  };

  const generateSequentialId = (categoria: string): string => {
    const cleanCategory = categoria.trim();
    const countInCategory = existingResources.filter(
      (p) => p.categoria?.toLowerCase() === cleanCategory.toLowerCase()
    ).length;

    const nextNumber = String(countInCategory + 1).padStart(3, "0");
    return `${cleanCategory}-${nextNumber}`;
  };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    const autoGeneratedId = resourceToEdit
      ? resourceToEdit.id
      : generateSequentialId(formData.categoria);

    const productToSave: Product = {
      id: autoGeneratedId,
      ...formData,
      fechaIngreso: new Date(formData.fechaIngreso),
    };

    onSave(productToSave);

    if (!resourceToEdit) {
      setFormData(initialFormState);
    }
  };

  // Clase base dinamicamente vinculada al acento para todos los campos de entrada
  const inputStyles = `mt-1 block w-full rounded-md border-gray-400 bg-white text-zinc-950 font-medium placeholder-gray-500 shadow-sm sm:text-sm p-2.5 border outline-none ${accent.borderFocus}`;

  return (
    <form onSubmit={handleSubmit} className="bg-white p-6 rounded-lg shadow-md border mb-6">
      <h2 className="text-xl font-extrabold mb-4 text-zinc-950">
        {resourceToEdit ? "Editar Recurso" : "Registrar Nuevo Recurso"}
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Nombre del Producto */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Nombre del Producto *
          </label>
          <input
            type="text"
            name="nombre"
            value={formData.nombre}
            onChange={handleChange}
            required
            className={inputStyles}
          />
        </div>

        {/* Categoría */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Categoría *
          </label>
          <select
            name="categoria"
            value={formData.categoria}
            onChange={handleChange}
            required
            className={inputStyles}
          >
            <option value="" className="text-gray-500">
              Seleccionar...
            </option>
            <option value="Redes">Redes</option>
            <option value="Computadoras">Computadoras</option>
            <option value="Audiovisuales">Audiovisuales</option>
            <option value="Periféricos">Periféricos</option>
            <option value="Insumos">Insumos Técnicos</option>
            <option value="Sensores">Sensores IoT</option>
            <option value="Arduino">Kits Arduino</option>
            <option value="Materiales">Materiales</option>
          </select>
        </div>

        {/* Cantidad */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Cantidad *
          </label>
          <input
            type="number"
            name="cantidad"
            placeholder="1"
            value={formData.cantidad}
            onChange={handleChange}
            required
            className={inputStyles}
          />
        </div>

        {/* Estado */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Estado *
          </label>
          <select
            name="estado"
            value={formData.estado}
            onChange={handleChange}
            required
            className={inputStyles}
          >
            <option value="Disponible">Disponible</option>
            <option value="En uso">En uso</option>
            <option value="En mantenimiento">En mantenimiento</option>
            <option value="No disponible">No disponible</option>
          </select>
        </div>

        {/* Ubicación */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Ubicación *
          </label>
          <input
            type="text"
            name="ubicacion"
            value={formData.ubicacion}
            onChange={handleChange}
            required
            className={inputStyles}
          />
        </div>

        {/* Responsable */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Responsable
          </label>
          <input
            type="text"
            name="responsable"
            value={formData.responsable}
            onChange={handleChange}
            className={inputStyles}
          />
        </div>

        {/* Fecha de Registro */}
        <div>
          <label className="block text-sm font-bold text-zinc-950 mb-1">
            Fecha de Registro *
          </label>
          <input
            type="date"
            name="fechaIngreso"
            value={formData.fechaIngreso}
            onChange={handleChange}
            required
            className={inputStyles}
          />
        </div>
      </div>

      {/* Descripción */}
      <div className="mt-4">
        <label className="block text-sm font-bold text-zinc-950 mb-1">
          Descripción
        </label>
        <textarea
          name="descripcion"
          value={formData.descripcion}
          onChange={handleChange}
          rows={3}
          className={inputStyles}
        ></textarea>
      </div>

      {/* Botones */}
      <div className="mt-6 flex gap-3">
        <button
          type="submit"
          className={`${accent.bgPrimary} font-bold px-5 py-2.5 rounded-md transition shadow-sm`}
        >
          {resourceToEdit ? "Guardar Cambios" : "Registrar Recurso"}
        </button>

        {resourceToEdit && onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="bg-gray-200 text-zinc-950 font-bold px-5 py-2.5 rounded-md hover:bg-gray-300 transition"
          >
            Cancelar Edición
          </button>
        )}
      </div>
    </form>
  );
}